import type { Metadata } from "next";
import "./globals.css";
import Layout from "@/components/Layout";
import { Roboto } from "next/font/google";

export const metadata: Metadata = {
  title: "Temple App",
  description: "Generated by Create Next App",
};

const roboto = Roboto({
  subsets: ["latin"],
  weight: "400",
});

// Fix for wrapping the entire layout properly
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.className}>
      <body>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
